name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: "22.3.4.1"
          elixir-version: "1.10.3"

      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install OTP and Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: "22.3.4.1"
          elixir-version: "1.10.3"

      - name: Compile
        run: MIX_ENV=test mix compile

      - name: Run tests
        run: mix test
